version: '3'

services:
  dpctf:
    container_name: dpctf
    image: dpctf:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8444:8444"
      - "9000:9000"
      #- "53:53/udp"
    network_mode: "bridge"
    volumes:
      - ./results:/home/ubuntu/DPCTF/results
      - ./config.json:/home/ubuntu/DPCTF/config.json
      - ./tests:/home/ubuntu/tests
      - ./content:/home/ubuntu/DPCTF/content
      - ./certs:/home/ubuntu/DPCTF/tools/certs
      #- ./test-config.json:/home/ubuntu/DPCTF/test-config.json
    environment:
      AGREE_EULA: "no"
      START_DNS: "yes"
    extra_hosts:
      - "www1.xn--n8j6ds53lwwkrqhv28a.web-platform.test:0.0.0.0"
      - "op88.web-platform.test:0.0.0.0"
      - "op36.not-web-platform.test:0.0.0.0"
      - "op53.not-web-platform.test:0.0.0.0"
      - "op50.not-web-platform.test:0.0.0.0"
      - "xn--lve-6lad.www.web-platform.test:0.0.0.0"
      - "op98.web-platform.test:0.0.0.0"
      - "op24.not-web-platform.test:0.0.0.0"
      - "op31.not-web-platform.test:0.0.0.0"
      - "op95.not-web-platform.test:0.0.0.0"
      - "op85.web-platform.test:0.0.0.0"
      - "op83.not-web-platform.test:0.0.0.0"
      - "www2.not-web-platform.test:0.0.0.0"
      - "xn--lve-6lad.www.not-web-platform.test:0.0.0.0"
      - "op73.not-web-platform.test:0.0.0.0"
      - "op8.web-platform.test:0.0.0.0"
      - "www2.www2.not-web-platform.test:0.0.0.0"
      - "op89.web-platform.test:0.0.0.0"
      - "op66.web-platform.test:0.0.0.0"
      - "xn--lve-6lad.web-platform.test:0.0.0.0"
      - "op19.not-web-platform.test:0.0.0.0"
      - "www1.www2.web-platform.test:0.0.0.0"
      - "op72.web-platform.test:0.0.0.0"
      - "op24.web-platform.test:0.0.0.0"
      - "op21.not-web-platform.test:0.0.0.0"
      - "xn--lve-6lad.not-web-platform.test:0.0.0.0"
      - "op41.web-platform.test:0.0.0.0"
      - "op79.web-platform.test:0.0.0.0"
      - "op81.not-web-platform.test:0.0.0.0"
      - "op70.not-web-platform.test:0.0.0.0"
      - "xn--n8j6ds53lwwkrqhv28a.xn--lve-6lad.not-web-platform.test:0.0.0.0"
      - "op78.not-web-platform.test:0.0.0.0"
      - "op6.not-web-platform.test:0.0.0.0"
      - "www1.www.not-web-platform.test:0.0.0.0"
      - "op40.not-web-platform.test:0.0.0.0"
      - "op25.not-web-platform.test:0.0.0.0"
      - "op3.not-web-platform.test:0.0.0.0"
      - "op65.not-web-platform.test:0.0.0.0"
      - "op91.web-platform.test:0.0.0.0"
      - "www.www2.web-platform.test:0.0.0.0"
      - "op80.not-web-platform.test:0.0.0.0"
      - "op59.web-platform.test:0.0.0.0"
      - "op52.not-web-platform.test:0.0.0.0"
      - "xn--lve-6lad.xn--lve-6lad.web-platform.test:0.0.0.0"
      - "op68.not-web-platform.test:0.0.0.0"
      - "op45.not-web-platform.test:0.0.0.0"
      - "op71.not-web-platform.test:0.0.0.0"
      - "op72.not-web-platform.test:0.0.0.0"
      - "xn--n8j6ds53lwwkrqhv28a.www2.web-platform.test:0.0.0.0"
      - "op39.web-platform.test:0.0.0.0"
      - "op90.not-web-platform.test:0.0.0.0"
      - "op60.web-platform.test:0.0.0.0"
      - "op58.web-platform.test:0.0.0.0"
      - "op28.web-platform.test:0.0.0.0"
      - "www1.web-platform.test:0.0.0.0"
      - "xn--n8j6ds53lwwkrqhv28a.xn--lve-6lad.web-platform.test:0.0.0.0"
      - "op14.web-platform.test:0.0.0.0"
      - "op89.not-web-platform.test:0.0.0.0"
      - "op69.web-platform.test:0.0.0.0"
      - "op49.not-web-platform.test:0.0.0.0"
      - "op40.web-platform.test:0.0.0.0"
      - "op2.not-web-platform.test:0.0.0.0"
      - "op5.not-web-platform.test:0.0.0.0"
      - "www.www2.not-web-platform.test:0.0.0.0"
      - "op77.not-web-platform.test:0.0.0.0"
      - "www.xn--n8j6ds53lwwkrqhv28a.web-platform.test:0.0.0.0"
      - "op7.web-platform.test:0.0.0.0"
      - "op74.web-platform.test:0.0.0.0"
      - "op79.not-web-platform.test:0.0.0.0"
      - "op82.not-web-platform.test:0.0.0.0"
      - "www.www1.web-platform.test:0.0.0.0"
      - "op12.not-web-platform.test:0.0.0.0"
      - "op39.not-web-platform.test:0.0.0.0"
      - "op31.web-platform.test:0.0.0.0"
      - "www.not-web-platform.test:0.0.0.0"
      - "www.www.not-web-platform.test:0.0.0.0"
      - "op44.not-web-platform.test:0.0.0.0"
      - "www1.not-web-platform.test:0.0.0.0"
      - "xn--n8j6ds53lwwkrqhv28a.www1.web-platform.test:0.0.0.0"
      - "op58.not-web-platform.test:0.0.0.0"
      - "op14.not-web-platform.test:0.0.0.0"
      - "op30.not-web-platform.test:0.0.0.0"
      - "op62.not-web-platform.test:0.0.0.0"
      - "op61.not-web-platform.test:0.0.0.0"
      - "op92.not-web-platform.test:0.0.0.0"
      - "www2.xn--lve-6lad.web-platform.test:0.0.0.0"
      - "op29.not-web-platform.test:0.0.0.0"
      - "op18.web-platform.test:0.0.0.0"
      - "op73.web-platform.test:0.0.0.0"
      - "xn--n8j6ds53lwwkrqhv28a.xn--n8j6ds53lwwkrqhv28a.web-platform.test:0.0.0.0"
      - "op77.web-platform.test:0.0.0.0"
      - "op12.web-platform.test:0.0.0.0"
      - "op54.web-platform.test:0.0.0.0"
      - "op63.web-platform.test:0.0.0.0"
      - "op71.web-platform.test:0.0.0.0"
      - "www2.www1.not-web-platform.test:0.0.0.0"
      - "op95.web-platform.test:0.0.0.0"
      - "op16.web-platform.test:0.0.0.0"
      - "op36.web-platform.test:0.0.0.0"
      - "op27.web-platform.test:0.0.0.0"
      - "www.www.web-platform.test:0.0.0.0"
      - "op98.not-web-platform.test:0.0.0.0"
      - "op64.not-web-platform.test:0.0.0.0"
      - "op29.web-platform.test:0.0.0.0"
      - "op9.web-platform.test:0.0.0.0"
      - "op26.not-web-platform.test:0.0.0.0"
      - "op22.not-web-platform.test:0.0.0.0"
      - "op94.web-platform.test:0.0.0.0"
      - "xn--n8j6ds53lwwkrqhv28a.www2.not-web-platform.test:0.0.0.0"
      - "op44.web-platform.test:0.0.0.0"
      - "op94.not-web-platform.test:0.0.0.0"
      - "op33.web-platform.test:0.0.0.0"
      - "op38.not-web-platform.test:0.0.0.0"
      - "op33.not-web-platform.test:0.0.0.0"
      - "op84.web-platform.test:0.0.0.0"
      - "www1.www1.not-web-platform.test:0.0.0.0"
      - "op23.not-web-platform.test:0.0.0.0"
      - "op57.not-web-platform.test:0.0.0.0"
      - "op54.not-web-platform.test:0.0.0.0"
      - "op85.not-web-platform.test:0.0.0.0"
      - "www2.www2.web-platform.test:0.0.0.0"
      - "op46.not-web-platform.test:0.0.0.0"
      - "op97.not-web-platform.test:0.0.0.0"
      - "op32.web-platform.test:0.0.0.0"
      - "op61.web-platform.test:0.0.0.0"
      - "op70.web-platform.test:0.0.0.0"
      - "www2.web-platform.test:0.0.0.0"
      - "op32.not-web-platform.test:0.0.0.0"
      - "op60.not-web-platform.test:0.0.0.0"
      - "op4.web-platform.test:0.0.0.0"
      - "op43.web-platform.test:0.0.0.0"
      - "op7.not-web-platform.test:0.0.0.0"
      - "op78.web-platform.test:0.0.0.0"
      - "op26.web-platform.test:0.0.0.0"
      - "xn--lve-6lad.xn--n8j6ds53lwwkrqhv28a.web-platform.test:0.0.0.0"
      - "op96.not-web-platform.test:0.0.0.0"
      - "op51.not-web-platform.test:0.0.0.0"
      - "op41.not-web-platform.test:0.0.0.0"
      - "op76.web-platform.test:0.0.0.0"
      - "op52.web-platform.test:0.0.0.0"
      - "op99.web-platform.test:0.0.0.0"
      - "op35.not-web-platform.test:0.0.0.0"
      - "op99.not-web-platform.test:0.0.0.0"
      - "op86.web-platform.test:0.0.0.0"
      - "not-web-platform.test:0.0.0.0"
      - "op42.not-web-platform.test:0.0.0.0"
      - "op46.web-platform.test:0.0.0.0"
      - "op67.not-web-platform.test:0.0.0.0"
      - "op17.web-platform.test:0.0.0.0"
      - "op90.web-platform.test:0.0.0.0"
      - "op93.web-platform.test:0.0.0.0"
      - "op37.not-web-platform.test:0.0.0.0"
      - "op48.not-web-platform.test:0.0.0.0"
      - "op10.web-platform.test:0.0.0.0"
      - "op55.not-web-platform.test:0.0.0.0"
      - "op4.not-web-platform.test:0.0.0.0"
      - "www1.xn--n8j6ds53lwwkrqhv28a.not-web-platform.test:0.0.0.0"
      - "op55.web-platform.test:0.0.0.0"
      - "xn--lve-6lad.www2.web-platform.test:0.0.0.0"
      - "op47.web-platform.test:0.0.0.0"
      - "op51.web-platform.test:0.0.0.0"
      - "op45.web-platform.test:0.0.0.0"
      - "op80.web-platform.test:0.0.0.0"
      - "op68.web-platform.test:0.0.0.0"
      - "op49.web-platform.test:0.0.0.0"
      - "op57.web-platform.test:0.0.0.0"
      - "www2.xn--n8j6ds53lwwkrqhv28a.web-platform.test:0.0.0.0"
      - "www.xn--n8j6ds53lwwkrqhv28a.not-web-platform.test:0.0.0.0"
      - "op56.not-web-platform.test:0.0.0.0"
      - "web-platform.test:0.0.0.0"
      - "op84.not-web-platform.test:0.0.0.0"
      - "xn--n8j6ds53lwwkrqhv28a.not-web-platform.test:0.0.0.0"
      - "xn--lve-6lad.xn--n8j6ds53lwwkrqhv28a.not-web-platform.test:0.0.0.0"
      - "op34.not-web-platform.test:0.0.0.0"
      - "op6.web-platform.test:0.0.0.0"
      - "op35.web-platform.test:0.0.0.0"
      - "op67.web-platform.test:0.0.0.0"
      - "op69.not-web-platform.test:0.0.0.0"
      - "op11.not-web-platform.test:0.0.0.0"
      - "op93.not-web-platform.test:0.0.0.0"
      - "www1.www.web-platform.test:0.0.0.0"
      - "op86.not-web-platform.test:0.0.0.0"
      - "op8.not-web-platform.test:0.0.0.0"
      - "www2.xn--n8j6ds53lwwkrqhv28a.not-web-platform.test:0.0.0.0"
      - "op92.web-platform.test:0.0.0.0"
      - "xn--lve-6lad.www1.not-web-platform.test:0.0.0.0"
      - "op15.web-platform.test:0.0.0.0"
      - "op13.not-web-platform.test:0.0.0.0"
      - "op13.web-platform.test:0.0.0.0"
      - "xn--n8j6ds53lwwkrqhv28a.web-platform.test:0.0.0.0"
      - "xn--n8j6ds53lwwkrqhv28a.www.web-platform.test:0.0.0.0"
      - "op75.web-platform.test:0.0.0.0"
      - "op20.not-web-platform.test:0.0.0.0"
      - "op76.not-web-platform.test:0.0.0.0"
      - "op64.web-platform.test:0.0.0.0"
      - "op97.web-platform.test:0.0.0.0"
      - "op37.web-platform.test:0.0.0.0"
      - "op56.web-platform.test:0.0.0.0"
      - "op62.web-platform.test:0.0.0.0"
      - "op82.web-platform.test:0.0.0.0"
      - "op25.web-platform.test:0.0.0.0"
      - "op11.web-platform.test:0.0.0.0"
      - "www.xn--lve-6lad.not-web-platform.test:0.0.0.0"
      - "www2.www1.web-platform.test:0.0.0.0"
      - "op27.not-web-platform.test:0.0.0.0"
      - "op50.web-platform.test:0.0.0.0"
      - "op17.not-web-platform.test:0.0.0.0"
      - "op38.web-platform.test:0.0.0.0"
      - "www2.www.not-web-platform.test:0.0.0.0"
      - "xn--lve-6lad.www1.web-platform.test:0.0.0.0"
      - "op75.not-web-platform.test:0.0.0.0"
      - "op83.web-platform.test:0.0.0.0"
      - "op81.web-platform.test:0.0.0.0"
      - "op15.not-web-platform.test:0.0.0.0"
      - "xn--n8j6ds53lwwkrqhv28a.www.not-web-platform.test:0.0.0.0"
      - "op20.web-platform.test:0.0.0.0"
      - "op3.web-platform.test:0.0.0.0"
      - "www1.www2.not-web-platform.test:0.0.0.0"
      - "xn--n8j6ds53lwwkrqhv28a.xn--n8j6ds53lwwkrqhv28a.not-web-platform.test:0.0.0.0"
      - "op2.web-platform.test:0.0.0.0"
      - "op21.web-platform.test:0.0.0.0"
      - "op23.web-platform.test:0.0.0.0"
      - "op42.web-platform.test:0.0.0.0"
      - "op47.not-web-platform.test:0.0.0.0"
      - "www1.www1.web-platform.test:0.0.0.0"
      - "op18.not-web-platform.test:0.0.0.0"
      - "op22.web-platform.test:0.0.0.0"
      - "xn--lve-6lad.xn--lve-6lad.not-web-platform.test:0.0.0.0"
      - "op63.not-web-platform.test:0.0.0.0"
      - "op28.not-web-platform.test:0.0.0.0"
      - "op65.web-platform.test:0.0.0.0"
      - "www.www1.not-web-platform.test:0.0.0.0"
      - "www1.xn--lve-6lad.web-platform.test:0.0.0.0"
      - "op43.not-web-platform.test:0.0.0.0"
      - "op66.not-web-platform.test:0.0.0.0"
      - "www2.www.web-platform.test:0.0.0.0"
      - "op96.web-platform.test:0.0.0.0"
      - "op91.not-web-platform.test:0.0.0.0"
      - "www.xn--lve-6lad.web-platform.test:0.0.0.0"
      - "op1.web-platform.test:0.0.0.0"
      - "op74.not-web-platform.test:0.0.0.0"
      - "op87.web-platform.test:0.0.0.0"
      - "op59.not-web-platform.test:0.0.0.0"
      - "op19.web-platform.test:0.0.0.0"
      - "xn--n8j6ds53lwwkrqhv28a.www1.not-web-platform.test:0.0.0.0"
      - "op9.not-web-platform.test:0.0.0.0"
      - "op88.not-web-platform.test:0.0.0.0"
      - "op53.web-platform.test:0.0.0.0"
      - "www2.xn--lve-6lad.not-web-platform.test:0.0.0.0"
      - "op87.not-web-platform.test:0.0.0.0"
      - "op30.web-platform.test:0.0.0.0"
      - "op10.not-web-platform.test:0.0.0.0"
      - "op48.web-platform.test:0.0.0.0"
      - "op16.not-web-platform.test:0.0.0.0"
      - "op34.web-platform.test:0.0.0.0"
      - "op1.not-web-platform.test:0.0.0.0"
      - "www.web-platform.test:0.0.0.0"
      - "op5.web-platform.test:0.0.0.0"
      - "www1.xn--lve-6lad.not-web-platform.test:0.0.0.0"
      - "xn--lve-6lad.www2.not-web-platform.test:0.0.0.0"
